trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'Run tests'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'   # Assuming your source code is in the root directory
    Contents: '**'                             # Copy all files
    TargetFolder: '$(Build.ArtifactStagingDirectory)/app'
  displayName: 'Copy files to staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/app'
    artifactName: 'webapp'
  displayName: 'Publish build artifacts'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'pipelineNodejs'
    appType: 'webAppLinux'
    WebAppName: 'microsoftCsuNodeJsApp2023'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/app'
    enableCustomDeployment: true
    slotName: ''                                      # Optional: Deployment slot name if needed
  displayName: 'Deploy to Azure Web App'
